### ISSUE TITLE
Not sending text for the checkbox field in the e-mail (only the Label is present)

### ISSUE THREAD

**Issue by Porscha-joomla** [zero-24/plg_fields_privacycheckbox#1]
Hi! The plugin is great. There are two things that I noticed:

1. In the plugin there is this sentence: "This plugin lets you create new fields of type 'checkbox' in any extensions where custom fields are supported." Maybe it's better to say "This plugin lets you create new fields of type 'privacycheckbox ' in any extensions where custom fields are supported." Because when somebody creates a custom field, it must be with type  Privacy Checkbox (privacycheckbox), not only checkbox.

2. After a privacy checkbox field is created and a text with <string> tags is placed in Checkbox Note, the permissions for Edit Custom Field Value are set to Allow, the contact form is ready for sending messages. When I tested it in the received e-mail in the site owner inbox, there is only a row with checkbox filed label, but there is no value and text for this field - basically the Checkbox note text is not in the email.

3. Default Value - it must not be filled, because the user freely has to give his permission, so for what is this field for?

**Comment by zero-24** [comment]
> Default Value - it must not be filled, because the user freely has to give his permission, so for what is this field for?

Joomla Core Custom Fields Field that all Custom Fields have

> After a privacy checkbox field is created and a text with tags is placed in Checkbox Note, the permissions for Edit Custom Field Value are set to Allow, the contact form is ready for sending messages. When I tested it in the received e-mail in the site owner inbox, there is only a row with checkbox filed label, but there is no value and text for this field - basically the Checkbox note text is not in the email.

As you have pointed out on 3 there is no default value so nothing to add here ;) As it is required to check that box you can not send a mail without it :)

> In the plugin there is this sentence: "This plugin lets you create new fields of type 'checkbox' in any extensions where custom fields are supported." Maybe it's better to say "This plugin lets you create new fields of type 'privacycheckbox ' in any extensions where custom fields are supported." Because when somebody creates a custom field, it must be with type Privacy Checkbox (privacycheckbox), not only checkbox.

Yes you are correct fixed with: https://github.com/zero-24/plg_fields_privacycheckbox/commit/f5a08094db0684738b7bfa8f3b30cde7d71a472d

**Comment by Porscha-joomla** [comment]
But after you check it and send the mail, the email receiver receives an email with all data as Name, Email and message, but the row where checkbox is, has only a label and : 
Example:
I have a label called: Privacy Policy agreement
and Checkbox note:  I consent to site storing and using my personal information to get back in touch with me. Link to Privacy Policy 
and in email which is received there is only Privacy Policy agreement: You do not have the sentence for the agreement. 
I do not know if I explained it very well.

**Comment by zero-24** [comment]
hmm I'm going to check that with a bit more time.

**Comment by Porscha-joomla** [comment]
Thank you! Maybe create a field with label and checkbox note, send an email and look at the email to see the last row in it should be the one with the custom field , but I personally have only the label in the mail.

**Comment by zero-24** [comment]
There is now a dedicated option for that text. In case nothing is there the Text "Checked" (`PLG_FIELDS_PRIVACYCHECKBOX_CHECKBOX_CHECKED`) is used.

https://github.com/zero-24/plg_fields_privacycheckbox/commit/a7217dfaf67ee522f7babf97f374f3f0c763a41d

Thanks for your suggestion.

**Comment by zero-24** [comment]
A new release including the change above got just published: https://github.com/zero-24/plg_fields_privacycheckbox/releases/tag/1.0.3
You can use the Joomla Updater from the Backend to update the plugin.

**Comment by Porscha-joomla** [comment]
Just great! Thank you @zero-24 :)
