### ISSUE TITLE
Checkbox not clickable

### ISSUE THREAD

**Issue by FDE68** [zero-24/plg_fields_privacycheckbox#12]
Plugin is newest version 1.05 - it is shown in contact-component but the checkbox is grey - so can´t be cklicked.
BUT the form also could be sent by klick on submit button.
Thanks for help / update
FDE

**Comment by zero-24** [comment]
Hi,

can you please double check in the permission tab of the field that the field permissions allow the Public the permission Edit Custom Field Value.

**Comment by FDE68** [comment]
Thanks for quick reply - sorry about my post, there was a misconfiguration of the individual field itself. It is working now.
Thanks a lot
FDE

**Comment by zero-24** [comment]
No problem. Will close the issue here :-)
