### ISSUE TITLE
params/privacycheckbox.xml 

### ISSUE THREAD

**Issue by LukasHH** [zero-24/plg_fields_privacycheckbox#2]
can you change the fieldtype textarea to editor? Then it is easier to design the text with links.
```
<?xml version="1.0" encoding="utf-8"?>
<form>
	<fields name="fieldparams">
		<fieldset name="fieldparams">
			<field
				name="textvalue"
				type="editor"
				width="90%"
				filter="safehtml"
				label="PLG_FIELDS_PRIVACYCHECKBOX_PARAMS_TEXTVALUE_LABEL"
			/>
		</fieldset>
	</fields>
</form>
```
![editor_field](https://user-images.githubusercontent.com/31522294/38329921-7bcd151c-384f-11e8-95fb-edadc49e2e97.PNG)

**Comment by zero-24** [comment]
Implemented with the commit https://github.com/zero-24/plg_fields_privacycheckbox/commit/a7217dfaf67ee522f7babf97f374f3f0c763a41d thanks for the suggestion. 👍

**Comment by zero-24** [comment]
A new release including the change above got just published: https://github.com/zero-24/plg_fields_privacycheckbox/releases/tag/1.0.3
You can use the Joomla Updater from the Backend to update the plugin.
