### ISSUE TITLE
Checkbox is disabled

### ISSUE THREAD

**Issue by thedod0** [zero-24/plg_fields_privacycheckbox#3]
I insert the box in contact formular, but its disabled. I cannot check the box.

**Comment by zero-24** [comment]
Please check the permissions you set on the custom field. It should allow edit value for public :-)

**Comment by thedod0** [comment]
Hello, permission set, same Problem :(

zero-24 <notifications@github.com> schrieb am Fr., 11. Mai 2018, 23:06:

**Comment by zero-24** [comment]
Please show me the permission on the custom field thanks.

**Comment by thedod0** [comment]
Its in German


zero-24 <notifications@github.com> schrieb am Sa., 12. Mai 2018, 00:54:

**Comment by thedod0** [comment]
Forget everything.... im stupid.. i checked the wrong "Public".. Thanks
Case closed

Dominik NY <olapa112@gmail.com> schrieb am Sa., 12. Mai 2018 um 10:09 Uhr:

**Comment by zero-24** [comment]
I'm from Germany too ;-) so that would not be a Problem. I'm going to open a issue to extend the documentation thanks!
