### ISSUE TITLE
Extend the install instructions

### ISSUE THREAD

**Issue by zero-24** [zero-24/plg_fields_privacycheckbox#4]
Extend the install instructions about the permisdion settings that need to be done / checked.

**Comment by coolcat-creations** [comment]
Thanks for the great field!!! What is email text for? I guess it belongs to this issue :)

**Comment by zero-24** [comment]
You can include a text to the email this is what this field is for. I think i get some time after the JSST Sprint is over to extend the description.

**Comment by coolcat-creations** [comment]
But which email and what kind of text? Something like "The user gave consent" ? Or it it for the mail copy the user gets? (It's not urgent to know but interesting)

**Comment by zero-24** [comment]
> But which email and what kind of text? Something like "The user gave consent" ? Or it it for the mail copy the user gets?

Yes. In the default cases: `Checked` next to the custom field in the mail (as value)
