### ISSUE TITLE
Can´t install plugin

### ISSUE THREAD

**Issue by DirkH69** [zero-24/plg_fields_privacycheckbox#5]
Hi, I´d love to try your plugin,

but I always get an error message about no installation file found. I got the newest Joomla version running!

I´d appreciate any help!

Best regards,
Dirk

**Comment by zero-24** [comment]
Hi,
what is the file you downloaded and what is your Joomla and PHP Versions? I have just installed the package (plg_fields_privacycheckbox.zip) from here: https://github.com/zero-24/plg_fields_privacycheckbox/releases/latest without any problem.

**Comment by DirkH69** [comment]
Thanks for your reply! I found out that my provider disabled any upload of new files because all my Joomla installations have to many files that I´m allowed to have! :-(

**Comment by zero-24** [comment]
Ok closing than 😄
