### ISSUE TITLE
Google ReCaptcha appears before this entry

### ISSUE THREAD

**Issue by KaeptnAmerica** [zero-24/plg_fields_privacycheckbox#6]
I've activated the Google ReCaptcha plugin to protect the site from beeing used as spammer. But as you can see in the screenshot, the ReCaptcha query appears before the custom field.
For user experience the ReCaptcha should be the last position shown prior to the send button.
Can you address this issue?
![recaptchabeforefield](https://user-images.githubusercontent.com/34630166/40419188-ce7cc784-5e84-11e8-9875-fbbbda23cd89.PNG)

You can take a look at: [Wildnaturefilm Homepage](http://www.wildnaturefilm.com/kontakt.html)

**Comment by zero-24** [comment]
> Can you address this issue?

No. Not inside my plugin but you can build an override that renders the custom fields over the captcha field.

**Comment by zero-24** [comment]
Closing for the reason above :)

**Comment by KaeptnAmerica** [comment]
Thank you for your input. I followed your suggestion and solved the problem by overriding the template. Thanks anyway.
