### ISSUE TITLE
optional privacycheckbox send 

### ISSUE THREAD

**Issue by ahurt2000** [zero-24/plg_fields_privacycheckbox#8]
Hello,
The 'emailtextvalue' is always sended. Even when is optional checkbox and is not checked.
Is any way to avoid it or change the text?
Thanks

**Comment by ahurt2000** [comment]
Trying this at fields/privacycheckbox/privacycheckbox.php seems work fine.

        if (!$field->value) {
            $emailTextValue = '';
        }

        if (empty($emailTextValue) && $field->required) {
            return Text::_('PLG_FIELDS_PRIVACYCHECKBOX_CHECKBOX_CHECKED');
        }

**Comment by zero-24** [comment]
> The 'emailtextvalue' is always sended. Even when is optional checkbox and is not checked.

Hi, can you please get a bit more into the details of your setup? The checkbox should never be optional as this is the whole point of that checkbox to be required.

> Is any way to avoid it or change the text?

You can change the text by overwriting the language string: `PLG_FIELDS_PRIVACYCHECKBOX_CHECKBOX_CHECKED` or providing an string in the options.

**Comment by zero-24** [comment]
@ahurt2000 Can I ask you to check the questions raised above? So we can fix the issue where required.

**Comment by zero-24** [comment]
@ahurt2000 please let me know when you have any updates here. For now Im going to close this as not possible to reproduce. Feel free to post any update here and I' happy to investigate.
